from __future__ import annotations

DEFAULT_CONFIG_FILENAME = "experiment.yaml"
DEFAULT_OUTPUT_DIR = "."
DEFAULT_PROJECT = "demo"
DEFAULT_EXPERIMENT = "baseline"
DEFAULT_STORAGE_ROOT = "./runs"
DEFAULT_PARTITION = "gpu"
DEFAULT_PYTHON_BIN = "python3"
DEFAULT_TRAIN_SCRIPT = "train.py"
DEFAULT_EVAL_SCRIPT = "eval.py"
DEFAULT_CHECKPOINT_PATH = "checkpoint.pt"

TEMPLATE_TRAIN_EVAL = "train-eval"
TEMPLATE_TRAIN_ONLY = "train-only"
TEMPLATE_EVAL_CHECKPOINT = "eval-checkpoint"

ALL_STARTER_TEMPLATES = (
    TEMPLATE_TRAIN_EVAL,
    TEMPLATE_TRAIN_ONLY,
    TEMPLATE_EVAL_CHECKPOINT,
)
TRAIN_TEMPLATES = (TEMPLATE_TRAIN_EVAL, TEMPLATE_TRAIN_ONLY)
EVAL_TEMPLATES = (TEMPLATE_TRAIN_EVAL, TEMPLATE_EVAL_CHECKPOINT)
