from __future__ import annotations

PACKAGE_NAME = "slurmforge"
__version__ = "0.1.3"


def regenerate_after_upgrade_note() -> str:
    return (
        f"Batches persist {PACKAGE_NAME} version metadata. "
        f"Upgrading {PACKAGE_NAME} may trigger compatibility warnings when executing or replaying older batches."
    )


def version_mismatch_warning(*, generated_by_name: str, generated_by_version: str) -> str:
    return (
        f"run record was generated by {generated_by_name} {generated_by_version}, "
        f"but the current {PACKAGE_NAME} is {__version__}. "
        "Continuing with a compatibility warning; regenerate the batch if execution behaves unexpectedly."
    )
