from __future__ import annotations

from .workflow_contract import (
    WORKFLOW_BLOCKED,
    WORKFLOW_FAILED,
    WORKFLOW_FINALIZING,
    WORKFLOW_PLANNED,
    WORKFLOW_STREAMING,
    WORKFLOW_SUCCESS,
)

INSTANCE_PLANNED = "planned"
INSTANCE_READY = "ready"
INSTANCE_SUBMITTED = "submitted"
INSTANCE_RUNNING = "running"
INSTANCE_SUCCESS = "success"
INSTANCE_FAILED = "failed"
INSTANCE_SKIPPED = "skipped"
INSTANCE_BLOCKED = "blocked"
INSTANCE_TERMINAL_STATES = (
    INSTANCE_SUCCESS,
    INSTANCE_FAILED,
    INSTANCE_SKIPPED,
    INSTANCE_BLOCKED,
)
INSTANCE_STATES = (
    INSTANCE_PLANNED,
    INSTANCE_READY,
    INSTANCE_SUBMITTED,
    INSTANCE_RUNNING,
    INSTANCE_SUCCESS,
    INSTANCE_FAILED,
    INSTANCE_SKIPPED,
    INSTANCE_BLOCKED,
)

DEPENDENCY_WAITING = "waiting"
DEPENDENCY_READY = "ready"
DEPENDENCY_RESOLVED = "resolved"
DEPENDENCY_BLOCKED = "blocked"
DEPENDENCY_STATES = (
    DEPENDENCY_WAITING,
    DEPENDENCY_READY,
    DEPENDENCY_RESOLVED,
    DEPENDENCY_BLOCKED,
)

DISPATCH_SUBMITTING = "submitting"
DISPATCH_SUBMITTED = "submitted"
DISPATCH_TERMINAL = "terminal"
DISPATCH_FAILED = "failed"
DISPATCH_ACTIVE_STATES = (DISPATCH_SUBMITTING, DISPATCH_SUBMITTED)
DISPATCH_STATES = (
    DISPATCH_SUBMITTING,
    DISPATCH_SUBMITTED,
    DISPATCH_TERMINAL,
    DISPATCH_FAILED,
)
DISPATCH_ROLE_INITIAL = "initial"
DISPATCH_ROLE_DISPATCH = "dispatch"
DISPATCH_ROLES = (DISPATCH_ROLE_INITIAL, DISPATCH_ROLE_DISPATCH)

RELEASE_PER_RUN = "per_run"
RELEASE_PER_GROUP = "per_group"
RELEASE_PER_STAGE = "per_stage"
RELEASE_WINDOWED = "windowed"
RELEASE_POLICIES = (
    RELEASE_PER_RUN,
    RELEASE_PER_GROUP,
    RELEASE_PER_STAGE,
    RELEASE_WINDOWED,
)

WORKFLOW_STATES = (
    WORKFLOW_PLANNED,
    WORKFLOW_STREAMING,
    WORKFLOW_FINALIZING,
    WORKFLOW_SUCCESS,
    WORKFLOW_FAILED,
    WORKFLOW_BLOCKED,
)

TERMINAL_AGGREGATION_PENDING = "pending"
TERMINAL_AGGREGATION_SUBMITTED = "submitted"
TERMINAL_AGGREGATION_FAILED = "failed"
TERMINAL_AGGREGATION_UNCERTAIN = "uncertain"
TERMINAL_AGGREGATION_DISABLED = "disabled"
TERMINAL_AGGREGATION_STATES = (
    TERMINAL_AGGREGATION_PENDING,
    TERMINAL_AGGREGATION_SUBMITTED,
    TERMINAL_AGGREGATION_FAILED,
    TERMINAL_AGGREGATION_UNCERTAIN,
    TERMINAL_AGGREGATION_DISABLED,
)

CONTROL_STATE_SUBMITTING = "submitting"
CONTROL_STATE_SUBMITTED = "submitted"
CONTROL_STATE_UNCERTAIN = "uncertain"
CONTROL_STATE_FAILED = "failed"
CONTROL_STATES = (
    CONTROL_STATE_SUBMITTING,
    CONTROL_STATE_SUBMITTED,
    CONTROL_STATE_UNCERTAIN,
    CONTROL_STATE_FAILED,
)

__all__ = [name for name in globals() if name.isupper()]
