from __future__ import annotations

import json
import tempfile
import unittest
import warnings
from dataclasses import replace
from pathlib import Path
from unittest.mock import patch

from slurmforge.pipeline.config.api import EvalTrainOutputsConfig
from slurmforge.pipeline.config.normalize import normalize_artifacts, normalize_env
from slurmforge.pipeline.planning.contracts import (
    AllocationRequest,
    ExecutionTopology,
    ResourceEstimate,
    StageCapabilities,
)
from slurmforge.pipeline.records import DispatchInfo
from tests._support import sample_run_plan, sample_stage_plan

from slurmforge.execution import run_plan
from slurmforge.execution import write_attempt_result as attempt_result_writer
from slurmforge.pipeline.materialization.blocks.common import q
from slurmforge.pipeline.status import (
    attempt_result_path_for_result_dir,
    read_attempt_result,
    read_execution_status,
    status_path_for_result_dir,
)


class RunPlanExecutorTests(unittest.TestCase):
    def _write_record_to_batch(self, tmp: Path, payload: dict, group_index: int = 1, task_index: int = 0) -> Path:
        """Write a run record JSON + storage descriptor into the canonical batch directory layout."""
        records_dir = tmp / "records" / f"group_{group_index:02d}"
        records_dir.mkdir(parents=True, exist_ok=True)
        record = records_dir / f"task_{task_index:06d}.json"
        record.write_text(json.dumps(payload), encoding="utf-8")
        from slurmforge.storage.descriptor import write_storage_descriptor
        from slurmforge.pipeline.config.api import StorageConfigSpec
        write_storage_descriptor(tmp, StorageConfigSpec(), tmp)
        return tmp

    def test_load_plan_rejects_invalid_platform_schema(self) -> None:
        from slurmforge.pipeline.records import serialize_run_plan

        plan = sample_run_plan()
        payload = serialize_run_plan(plan)
        payload["env"] = []
        with tempfile.TemporaryDirectory() as tmp:
            batch_root = self._write_record_to_batch(Path(tmp), payload)
            with self.assertRaisesRegex(ValueError, "env must be a mapping"):
                run_plan.load_plan(batch_root, group_index=1, task_index=0)

    def test_load_plan_warns_when_run_record_generated_by_different_slurmforge_version(self) -> None:
        from slurmforge.pipeline.records import serialize_run_plan

        plan = sample_run_plan()
        payload = serialize_run_plan(plan)
        payload["generated_by"]["version"] = "9.9.9"

        with tempfile.TemporaryDirectory() as tmp:
            batch_root = self._write_record_to_batch(Path(tmp), payload)
            with warnings.catch_warnings(record=True) as caught:
                warnings.simplefilter("always")
                restored = run_plan.load_plan(batch_root, group_index=1, task_index=0)

        self.assertEqual(restored.run_id, plan.run_id)
        self.assertTrue(any("generated by slurmforge 9.9.9" in str(item.message) for item in caught))

    def test_run_plan_executor_reads_nested_dispatch_fields(self) -> None:
        plan = sample_run_plan(
            dispatch=replace(
                DispatchInfo(),
                record_path=str(Path("/tmp/run_1") / "records" / "group_01" / "task_000001.json"),
                array_group=2,
                array_task_index=5,
            )
        )
        script = run_plan.build_shell_script(plan)
        self.assertIn("[BATCH] array_group=2", script)
        self.assertIn("[BATCH] array_task_index=5", script)
        self.assertIn('export AI_INFRA_META_DIR="${META_DIR}"', script)
        self.assertIn(
            f"export AI_INFRA_EXECUTION_PLAN_JSON_PATH={q(str(Path(plan.run_dir) / 'records' / 'group_01' / 'task_000001.json'))}",
            script,
        )

    def test_run_plan_executor_includes_runtime_preflight(self) -> None:
        train_stage = sample_stage_plan(
            topology=ExecutionTopology(nodes=1, processes_per_node=4, master_port=29500),
            allocation=AllocationRequest(nodes=1, gpus_per_node=4, cpus_per_task=8, mem="0"),
            estimate=ResourceEstimate(2, 4, 4, 32.0, "estimate"),
            capabilities=StageCapabilities(True, False, True, False, "cuda"),
        )
        plan = sample_run_plan(train_stage=train_stage)

        script = run_plan.build_shell_script(plan)

        self.assertIn("CUDA_VISIBLE_DEVICES", script)
        self.assertIn("torch.cuda.device_count()", script)
        self.assertIn("EXPECTED_PROCESSES_PER_NODE=4", script)

    def test_run_plan_executor_preflight_uses_stage_python_bin(self) -> None:
        plan = sample_run_plan(
            train_stage=sample_stage_plan(
                python_bin="/tmp/custom-python",
                topology=ExecutionTopology(nodes=1, processes_per_node=2, master_port=29500),
                allocation=AllocationRequest(nodes=1, gpus_per_node=2, cpus_per_task=8, mem="0"),
                estimate=ResourceEstimate(1, 2, 2, 16.0, "estimate"),
            )
        )

        script = run_plan.build_shell_script(plan)

        self.assertIn("/tmp/custom-python - <<'PY'", script)
        self.assertIn("/tmp/custom-python -c", script)

    def test_run_plan_executor_wraps_multinode_ddp_train_with_srun_and_master_addr_resolution(self) -> None:
        plan = sample_run_plan(
            train_stage=sample_stage_plan(
                launcher_kind="ddp",
                command_text="torchrun --nnodes=2 --node_rank=${SLURM_NODEID:-0} --master_addr=${MASTER_ADDR} --master_port=29500 train.py",
                topology=ExecutionTopology(nodes=2, processes_per_node=4, master_port=29500),
                allocation=AllocationRequest(nodes=2, gpus_per_node=4, cpus_per_task=8, mem="0"),
                estimate=ResourceEstimate(4, 8, 8, 64.0, "estimate"),
            )
        )

        script = run_plan.build_shell_script(plan)

        self.assertIn('export AI_INFRA_TRAIN_RUNTIME_NNODES=2', script)
        self.assertIn('export AI_INFRA_TRAIN_MASTER_PORT=29500', script)
        self.assertIn('scontrol show hostnames "${SLURM_JOB_NODELIST}" | head -n 1', script)
        self.assertIn('srun --ntasks="${AI_INFRA_TRAIN_RUNTIME_NNODES}" --ntasks-per-node=1', script)

    def test_run_plan_executor_eval_raw_command_preserves_shell_text(self) -> None:
        plan = sample_run_plan(
            eval_stage=sample_stage_plan(
                name="eval",
                stage_kind="eval",
                invocation_kind="external_command",
                launcher_kind="external",
                command_text="bash eval.sh | sed 's/x/y/'",
                command_mode="raw",
                script_path=None,
            )
        )

        script = run_plan.build_shell_script(plan)

        self.assertIn('bash eval.sh | sed \'s/x/y/\' > "${LOG_DIR}/eval.log" 2>&1', script)
        self.assertIn("eval_command_mode=raw", script)

    def test_run_plan_executor_generates_train_output_contract_before_eval(self) -> None:
        plan = sample_run_plan(
            eval_stage=sample_stage_plan(
                name="eval",
                stage_kind="eval",
                invocation_kind="eval_script",
                launcher_kind="single",
                command_text="python3 eval.py",
            ),
            eval_train_outputs=EvalTrainOutputsConfig(required=True, checkpoint_policy="best"),
            artifacts=normalize_artifacts({"checkpoint_globs": ["checkpoints/**/*.ckpt"]}),
        )

        script = run_plan.build_shell_script(plan)

        self.assertIn('export AI_INFRA_TRAIN_ARTIFACT_MANIFEST="${META_DIR}/train_outputs.json"', script)
        self.assertIn('TRAIN_OUTPUTS_BIN="${AI_INFRA_WRITE_TRAIN_OUTPUTS_BIN:-sforge-write-train-outputs}"', script)
        self.assertIn("TRAIN_OUTPUTS_CMD+=(--require_primary)", script)
        self.assertIn("--primary_policy best", script)
        self.assertIn(f"TRAIN_OUTPUTS_CMD+=(--workdir {q(plan.train_stage.workdir)})", script)
        self.assertIn('TRAIN_OUTPUTS_CMD+=(--checkpoint_glob \'checkpoints/**/*.ckpt\')', script)
        self.assertIn('. "${TRAIN_OUTPUT_ENV_PATH}"', script)
        self.assertIn('skipped because train output handoff failed', script)

    def test_run_plan_executor_rejects_unsafe_activate_commands(self) -> None:
        plan = sample_run_plan(env=normalize_env({"conda_activate": "source ~/miniconda3/bin/activate && rm -rf /"}))
        with self.assertRaisesRegex(ValueError, "env\\.conda_activate contains unsafe shell token"):
            run_plan.build_shell_script(plan)

    def test_execute_plan_writes_execution_status_for_failed_train(self) -> None:
        plan = sample_run_plan()
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            batch_root = tmp_path / "batch"
            batch_root.mkdir()
            plan = replace(plan, run_dir=str(batch_root / "run_001"))

            # Write a minimal storage descriptor so open_batch_storage works
            from slurmforge.storage.descriptor import write_storage_descriptor
            from slurmforge.pipeline.config.api import StorageConfigSpec
            (batch_root / "meta").mkdir(parents=True, exist_ok=True)
            write_storage_descriptor(batch_root, StorageConfigSpec(), batch_root)

            def _fake_execute(_script: str) -> int:
                result_dir = Path(plan.run_dir) / "job-na_na"
                (result_dir / "meta").mkdir(parents=True, exist_ok=True)
                from slurmforge.storage.execution.journal import write_attempt_result as _write_ar
                from slurmforge.pipeline.status import build_attempt_result
                attempt = build_attempt_result(result_dir=result_dir, train_exit_code=5, eval_exit_code=0)
                _write_ar(result_dir, attempt)
                return 5

            with patch("slurmforge.execution.run_plan.api.execute_script", side_effect=_fake_execute):
                with patch("slurmforge.execution.run_plan.api.build_shell_script", return_value="#!/usr/bin/env bash\n"):
                    exit_code = run_plan.execute_plan(plan, batch_root=batch_root)

            attempt = read_attempt_result(attempt_result_path_for_result_dir(Path(plan.run_dir) / "job-na_na"))
            status = read_execution_status(status_path_for_result_dir(Path(plan.run_dir) / "job-na_na"))

        self.assertEqual(exit_code, 5)
        self.assertIsNotNone(attempt)
        self.assertEqual(attempt.train_exit_code, 5)
        self.assertIsNotNone(status)
        self.assertEqual(status.state, "failed")
        self.assertEqual(status.failure_class, "script_error")
