from __future__ import annotations

from .options import (
    ARTIFACT_STRATEGY_COPY,
    DISPATCH_POLICY_SERIALIZE_GROUPS,
    EMAIL_EVENT_BATCH_FINISHED,
    EMAIL_MODE_SUMMARY,
    ENTRY_PYTHON_SCRIPT,
    INPUT_EXPECTS_PATH,
    INPUT_INJECT_PATH,
    LAUNCHER_MODE_SINGLE_NODE,
    LAUNCHER_SINGLE,
    OUTPUT_SELECT_LATEST_STEP,
    RUN_SINGLE,
)

DEFAULT_CONFIG_FILENAME = "experiment.yaml"
DEFAULT_OUTPUT_DIR = "."

DEFAULT_PROJECT = "demo"
DEFAULT_EXPERIMENT = "baseline"
DEFAULT_STORAGE_ROOT = "./runs"

AUTO_VALUE = "auto"

DEFAULT_PARTITION = "gpu"
DEFAULT_PYTHON_BIN = "python3"
DEFAULT_PYTHON_MIN_VERSION = "3.10"
DEFAULT_EXECUTOR_MODULE = "slurmforge.executor.stage"
DEFAULT_TRAIN_SCRIPT = "train.py"
DEFAULT_EVAL_SCRIPT = "eval.py"
DEFAULT_CHECKPOINT_PATH = "checkpoint.pt"

DEFAULT_ENVIRONMENT_NAME = "default"
DEFAULT_RUNTIME_NAME = "default"

DEFAULT_RUN_TYPE = RUN_SINGLE

DEFAULT_ARTIFACT_STORE_STRATEGY = ARTIFACT_STRATEGY_COPY
DEFAULT_ARTIFACT_STORE_FALLBACK_STRATEGY = None
DEFAULT_ARTIFACT_STORE_VERIFY_DIGEST = True
DEFAULT_ARTIFACT_STORE_FAIL_ON_VERIFY_ERROR = True

DEFAULT_DISPATCH_MAX_AVAILABLE_GPUS = 1
DEFAULT_DISPATCH_OVERFLOW_POLICY = DISPATCH_POLICY_SERIALIZE_GROUPS

DEFAULT_CONTROLLER_CPUS = 1
DEFAULT_CONTROLLER_MEM = "2G"
DEFAULT_CONTROLLER_TIME_LIMIT = "01:00:00"
DEFAULT_CONTROLLER_ENVIRONMENT = DEFAULT_ENVIRONMENT_NAME

DEFAULT_STAGE_ENABLED = True
DEFAULT_STAGE_ENTRY_TYPE = ENTRY_PYTHON_SCRIPT
DEFAULT_STAGE_ENTRY_WORKDIR = "."
DEFAULT_STAGE_LAUNCHER_TYPE = LAUNCHER_SINGLE
DEFAULT_STAGE_ENVIRONMENT = DEFAULT_ENVIRONMENT_NAME
DEFAULT_STAGE_RUNTIME = DEFAULT_RUNTIME_NAME

DEFAULT_STAGE_RESOURCES_PARTITION = DEFAULT_PARTITION
DEFAULT_STAGE_RESOURCES_NODES = 1
DEFAULT_STAGE_RESOURCES_GPUS_PER_NODE = 1
DEFAULT_STAGE_RESOURCES_CPUS_PER_TASK = 1
DEFAULT_STAGE_RESOURCES_TIME_LIMIT = "01:00:00"

DEFAULT_LAUNCHER_MODE = LAUNCHER_MODE_SINGLE_NODE
DEFAULT_LAUNCHER_NNODES = AUTO_VALUE
DEFAULT_LAUNCHER_NPROC_PER_NODE = AUTO_VALUE
DEFAULT_RENDEZVOUS_BACKEND = "c10d"
DEFAULT_RENDEZVOUS_ENDPOINT = AUTO_VALUE
DEFAULT_RENDEZVOUS_PORT = 29500

DEFAULT_GPU_SIZING_MIN_GPUS_PER_JOB = 1
DEFAULT_GPU_SIZING_SAFETY_FACTOR = 1.0
DEFAULT_GPU_SIZING_ROUND_TO = 1

DEFAULT_INPUT_EXPECTS = INPUT_EXPECTS_PATH
DEFAULT_INPUT_INJECT_MODE = INPUT_INJECT_PATH
DEFAULT_OUTPUT_REQUIRED = False
DEFAULT_OUTPUT_JSON_PATH = "$"
DEFAULT_OUTPUT_DISCOVER_SELECT = OUTPUT_SELECT_LATEST_STEP

DEFAULT_EMAIL_ENABLED = False
DEFAULT_EMAIL_EVENTS = (EMAIL_EVENT_BATCH_FINISHED,)
DEFAULT_EMAIL_MODE = EMAIL_MODE_SUMMARY
DEFAULT_EMAIL_FROM = "slurmforge@localhost"
DEFAULT_EMAIL_SENDMAIL = "/usr/sbin/sendmail"
DEFAULT_EMAIL_SUBJECT_PREFIX = "SlurmForge"

__all__ = [
    name for name in globals() if name == "AUTO_VALUE" or name.startswith("DEFAULT_")
]
