from __future__ import annotations

from ..workflow_contract import EVAL_STAGE, TRAIN_STAGE


STAGE_TRAIN = TRAIN_STAGE
STAGE_EVAL = EVAL_STAGE
SUPPORTED_STAGE_KEYS = frozenset({STAGE_TRAIN, STAGE_EVAL})

TEMPLATE_TRAIN_EVAL = "train-eval"
TEMPLATE_TRAIN_ONLY = "train-only"
TEMPLATE_EVAL_CHECKPOINT = "eval-checkpoint"

ALL_STARTER_TEMPLATES = (
    TEMPLATE_TRAIN_EVAL,
    TEMPLATE_TRAIN_ONLY,
    TEMPLATE_EVAL_CHECKPOINT,
)
TRAIN_TEMPLATES = (TEMPLATE_TRAIN_EVAL, TEMPLATE_TRAIN_ONLY)
EVAL_TEMPLATES = (TEMPLATE_TRAIN_EVAL, TEMPLATE_EVAL_CHECKPOINT)

__all__ = [name for name in globals() if name.isupper()]
