from __future__ import annotations

from typing import Final

from ...defaults import ALL_STARTER_TEMPLATES
from ..models import ConfigField, ConfigOption

FIELDS: Final[tuple[ConfigField, ...]] = (
    ConfigField(
        path="stages.*.launcher.type",
        title="Launcher type",
        short_help="Chooses how a stage process is launched.",
        when_to_change="Keep single for normal scripts; use torchrun, srun, mpirun, or command for distributed/custom launch.",
        section="Launcher",
        level="advanced",
        templates=ALL_STARTER_TEMPLATES,
        default="single",
        options=(
            ConfigOption("single", "Run one process directly."),
            ConfigOption("python", "Launch through Python."),
            ConfigOption("torchrun", "Launch distributed PyTorch."),
            ConfigOption("srun", "Launch through Slurm srun."),
            ConfigOption("mpirun", "Launch through MPI."),
            ConfigOption("command", "Launch a raw command."),
        ),
    ),
    ConfigField(
        path="stages.*.launcher.mode",
        title="Launcher node mode",
        short_help="Declares whether launch happens on one node or across multiple nodes.",
        when_to_change="Use multi_node only when the selected launcher and resources are configured for multi-node jobs.",
        section="Launcher",
        level="advanced",
        templates=ALL_STARTER_TEMPLATES,
        default="single_node",
        options=(
            ConfigOption("single_node", "Launch on one node."),
            ConfigOption("multi_node", "Launch across multiple nodes."),
        ),
    ),
    ConfigField(
        path="stages.*.launcher.nnodes",
        title="Launcher node count",
        short_help="Node count passed to distributed launchers, or auto from resources.nodes.",
        when_to_change="Set this explicitly when a launcher requires a concrete node count.",
        section="Launcher",
        level="advanced",
        value_type="integer-or-auto",
        templates=ALL_STARTER_TEMPLATES,
        default="auto",
    ),
    ConfigField(
        path="stages.*.launcher.nproc_per_node",
        title="Launcher processes per node",
        short_help="Process count per node passed to distributed launchers, or auto from resolved GPUs per node.",
        when_to_change="Set this when process count should differ from the resolved GPU count.",
        section="Launcher",
        level="advanced",
        value_type="integer-or-auto",
        templates=ALL_STARTER_TEMPLATES,
        default="auto",
    ),
    ConfigField(
        path="stages.*.launcher.rendezvous",
        title="Launcher rendezvous",
        short_help="Distributed rendezvous settings for torchrun launchers.",
        when_to_change="Set this for multi-node torchrun jobs that need an explicit backend, endpoint, or port.",
        section="Launcher",
        level="advanced",
        value_type="mapping",
        templates=ALL_STARTER_TEMPLATES,
        default="backend=c10d, endpoint=auto, port=29500",
    ),
    ConfigField(
        path="stages.*.launcher.rendezvous.backend",
        title="Launcher rendezvous backend",
        short_help="Rendezvous backend passed to torchrun.",
        when_to_change="Change this only when your distributed runtime requires a non-default backend.",
        section="Launcher",
        level="advanced",
        templates=ALL_STARTER_TEMPLATES,
        default="c10d",
    ),
    ConfigField(
        path="stages.*.launcher.rendezvous.endpoint",
        title="Launcher rendezvous endpoint",
        short_help="Rendezvous endpoint passed to torchrun.",
        when_to_change="Use auto for Slurm-managed multi-node jobs; set a value only for custom rendezvous wiring.",
        section="Launcher",
        level="advanced",
        templates=ALL_STARTER_TEMPLATES,
        default="auto",
    ),
    ConfigField(
        path="stages.*.launcher.rendezvous.port",
        title="Launcher rendezvous port",
        short_help="TCP port used by torchrun rendezvous.",
        when_to_change="Change this when the default port conflicts with site policy or another service.",
        section="Launcher",
        level="advanced",
        value_type="port",
        templates=ALL_STARTER_TEMPLATES,
        default="29500",
    ),
    ConfigField(
        path="stages.*.launcher.args",
        title="Launcher arguments",
        short_help="Raw arguments passed to srun or mpirun launchers.",
        when_to_change="Use this for launcher-specific flags that are not modeled as first-class fields.",
        section="Launcher",
        level="advanced",
        value_type="list",
        templates=ALL_STARTER_TEMPLATES,
        default="[]",
    ),
    ConfigField(
        path="stages.*.launcher.srun_args",
        title="Torchrun srun arguments",
        short_help="Raw srun arguments used by multi-node torchrun launch.",
        when_to_change="Use this for Slurm flags required by the torchrun bootstrap step.",
        section="Launcher",
        level="advanced",
        value_type="list",
        templates=ALL_STARTER_TEMPLATES,
        default="[]",
    ),
)
