from __future__ import annotations

from typing import Final

from ...defaults import (
    ALL_STARTER_TEMPLATES,
    DEFAULT_PYTHON_BIN,
)
from ..models import ConfigField

FIELDS: Final[tuple[ConfigField, ...]] = (
    ConfigField(
        path="environments.*.modules",
        title="Environment modules",
        short_help="Module names loaded before executor and user scripts run.",
        when_to_change="Add cluster modules such as CUDA, compiler, MPI, or Python stacks required by your jobs.",
        section="Runtime",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default="[]",
    ),
    ConfigField(
        path="environments.*.source",
        title="Environment sources",
        short_help="Shell files or setup commands sourced before execution.",
        when_to_change="Use this for virtualenv, conda, or site-specific setup that must run inside Slurm jobs.",
        section="Runtime",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default="[]",
    ),
    ConfigField(
        path="environments.*.source[].path",
        title="Environment source path",
        short_help="Shell file sourced before execution.",
        when_to_change="Use this for conda activation, virtualenv activation, or site setup scripts.",
        section="Runtime",
        level="intermediate",
        value_type="path",
        templates=ALL_STARTER_TEMPLATES,
        default="template-specific",
    ),
    ConfigField(
        path="environments.*.source[].args",
        title="Environment source arguments",
        short_help="Arguments passed to the sourced setup file.",
        when_to_change="Use this when a setup script accepts mode, environment, or module arguments.",
        section="Runtime",
        level="advanced",
        value_type="list",
        templates=ALL_STARTER_TEMPLATES,
        default="[]",
    ),
    ConfigField(
        path="environments.*.env",
        title="Environment variables",
        short_help="Static environment variables added to Slurm job environments.",
        when_to_change="Add paths, tokens, offline cache settings, or framework environment knobs required by scripts.",
        section="Runtime",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default="{}",
    ),
    ConfigField(
        path="runtime.executor.python.bin",
        title="Executor Python",
        short_help="Python used by the SlurmForge executor wrapper on compute nodes.",
        when_to_change="Change this when compute nodes need a different Python command to import slurmforge.",
        section="Runtime",
        level="common",
        templates=ALL_STARTER_TEMPLATES,
        default=DEFAULT_PYTHON_BIN,
        first_edit=True,
    ),
    ConfigField(
        path="runtime.executor.python.min_version",
        title="Executor Python minimum version",
        short_help="Minimum Python version required for the SlurmForge executor.",
        when_to_change="Change only when the executor runtime contract changes.",
        section="Runtime",
        level="advanced",
        value_type="version",
        templates=ALL_STARTER_TEMPLATES,
        default="3.10",
    ),
    ConfigField(
        path="runtime.executor.module",
        title="Executor module",
        short_help="Python module used as the SlurmForge stage executor entrypoint.",
        when_to_change="Most workflows should keep the packaged executor module.",
        section="Runtime",
        level="advanced",
        value_type="python-module",
        templates=ALL_STARTER_TEMPLATES,
        default="slurmforge.executor.stage",
    ),
    ConfigField(
        path="runtime.user.*.python.bin",
        title="User script Python",
        short_help="Python used to run generated train/eval scripts.",
        when_to_change="Change this to the Python environment that contains your model dependencies.",
        section="Runtime",
        level="common",
        templates=ALL_STARTER_TEMPLATES,
        default=DEFAULT_PYTHON_BIN,
        first_edit=True,
    ),
    ConfigField(
        path="runtime.user.*.python.min_version",
        title="User Python minimum version",
        short_help="Minimum Python version required for user stage scripts.",
        when_to_change="Change this when your user runtime intentionally targets another Python version.",
        section="Runtime",
        level="advanced",
        value_type="version",
        templates=ALL_STARTER_TEMPLATES,
        default="3.10",
    ),
    ConfigField(
        path="runtime.user.*.env",
        title="User runtime environment variables",
        short_help="Environment variables visible to user stage scripts.",
        when_to_change="Use this for variables that should apply to all scripts using the default user runtime.",
        section="Runtime",
        level="intermediate",
        value_type="mapping",
        templates=ALL_STARTER_TEMPLATES,
        default="{}",
    ),
)
