from __future__ import annotations

from typing import Final

from ...defaults import (
    ALL_STARTER_TEMPLATES,
    DEFAULT_CHECKPOINT_PATH,
    EVAL_TEMPLATES,
    TEMPLATE_TRAIN_EVAL,
    TRAIN_TEMPLATES,
)
from ..models import ConfigField, ConfigOption

FIELDS: Final[tuple[ConfigField, ...]] = (
    ConfigField(
        path="stages.*.depends_on",
        title="Stage dependencies",
        short_help="Upstream stage names that must complete before this stage is selected.",
        when_to_change="Set this when a stage consumes outputs from earlier stages.",
        section="Stage IO",
        level="intermediate",
        value_type="list",
        templates=(TEMPLATE_TRAIN_EVAL,),
        default="template-specific",
        required=False,
    ),
    ConfigField(
        path="stages.train.outputs.checkpoint",
        title="Train checkpoint output",
        short_help="Declared checkpoint contract produced by the train stage.",
        when_to_change="Change the discovery glob if your training code writes checkpoints somewhere else.",
        section="Stage IO",
        level="common",
        templates=TRAIN_TEMPLATES,
        default="checkpoints/**/*.pt",
        first_edit=True,
    ),
    ConfigField(
        path="stages.eval.inputs.checkpoint",
        title="Eval checkpoint input",
        short_help="Checkpoint input consumed by the eval stage.",
        when_to_change="For train-eval keep upstream_output; for eval-checkpoint replace the sample external path.",
        section="Stage IO",
        level="common",
        templates=EVAL_TEMPLATES,
        default="template-specific",
        first_edit=True,
    ),
    ConfigField(
        path="stages.eval.outputs.accuracy",
        title="Eval metric output",
        short_help="Declared accuracy metric read from eval/metrics.json.",
        when_to_change="Change this if evaluation writes a different metric file or JSON path.",
        section="Stage IO",
        level="common",
        templates=EVAL_TEMPLATES,
        default="eval/metrics.json $.accuracy",
        first_edit=True,
    ),
    ConfigField(
        path="stages.*.inputs.*.source.kind",
        title="Input source kind",
        short_help="Controls where a stage input is resolved from.",
        when_to_change="Use upstream_output for pipeline dependencies and external_path for user-provided files.",
        section="Stage IO",
        level="intermediate",
        templates=EVAL_TEMPLATES,
        default="template-specific",
        options=(
            ConfigOption("upstream_output", "Read an output from a previous stage."),
            ConfigOption("external_path", "Read an explicit user-provided path."),
        ),
        required=True,
    ),
    ConfigField(
        path="stages.*.inputs.*.source.stage",
        title="Input source stage",
        short_help="Producer stage name for an upstream output input.",
        when_to_change="Change this when the input should consume a different upstream producer.",
        section="Stage IO",
        level="intermediate",
        templates=(TEMPLATE_TRAIN_EVAL,),
        default="train",
        required=None,
    ),
    ConfigField(
        path="stages.*.inputs.*.source.output",
        title="Input source output",
        short_help="Producer output name resolved from the upstream stage.",
        when_to_change="Change this when the producer stage exposes a different output contract.",
        section="Stage IO",
        level="intermediate",
        templates=(TEMPLATE_TRAIN_EVAL,),
        default="checkpoint",
        required=None,
    ),
    ConfigField(
        path="stages.*.inputs.*.source.path",
        title="External input path",
        short_help="Explicit user-provided input path resolved relative to the config directory.",
        when_to_change="Replace the starter sample path with the real artifact path before submit.",
        section="Stage IO",
        level="common",
        value_type="path",
        templates=EVAL_TEMPLATES,
        default=DEFAULT_CHECKPOINT_PATH,
        required=None,
    ),
    ConfigField(
        path="stages.*.inputs.*.expects",
        title="Input expected shape",
        short_help="Declares the resolved input shape expected by the consuming stage.",
        when_to_change="Change this when passing a manifest payload or scalar value instead of a filesystem path.",
        section="Stage IO",
        level="intermediate",
        templates=EVAL_TEMPLATES,
        default="path",
        options=(
            ConfigOption("path", "Inject a filesystem path."),
            ConfigOption("manifest", "Inject a manifest payload."),
            ConfigOption("value", "Inject a scalar value."),
        ),
        required=False,
    ),
    ConfigField(
        path="stages.*.inputs.*.required",
        title="Input required flag",
        short_help="Controls whether a missing resolved input fails the stage plan.",
        when_to_change="Enable this for inputs that are mandatory for correct stage execution.",
        section="Stage IO",
        level="intermediate",
        value_type="boolean",
        templates=EVAL_TEMPLATES,
        default="false",
        required=False,
    ),
    ConfigField(
        path="stages.*.inputs.*.inject.mode",
        title="Input injection mode",
        short_help="Controls how a resolved input is injected into the stage process.",
        when_to_change="Use json for structured payloads or value for scalar values.",
        section="Stage IO",
        level="intermediate",
        templates=EVAL_TEMPLATES,
        default="path",
        options=(
            ConfigOption("path", "Pass the resolved input path."),
            ConfigOption("value", "Pass the resolved input value."),
            ConfigOption("json", "Pass the resolved input encoded as JSON."),
        ),
        required=False,
    ),
    ConfigField(
        path="stages.*.inputs.*.inject.flag",
        title="Input CLI flag",
        short_help="CLI flag name used to pass the resolved input to the stage process.",
        when_to_change="Change this to match the argument name accepted by your script.",
        section="Stage IO",
        level="common",
        templates=EVAL_TEMPLATES,
        default="checkpoint_path",
        required=False,
    ),
    ConfigField(
        path="stages.*.inputs.*.inject.env",
        title="Input environment variable",
        short_help="Environment variable used to pass the resolved input to the stage process.",
        when_to_change="Change this when the script expects a different environment variable name.",
        section="Stage IO",
        level="intermediate",
        templates=EVAL_TEMPLATES,
        default="SFORGE_INPUT_CHECKPOINT",
        required=False,
    ),
    ConfigField(
        path="stages.*.outputs.*.kind",
        title="Output kind",
        short_help="Declares the shape of a managed stage output.",
        when_to_change="Use file/files for artifacts, metric for JSON scalar metrics, and manifest for manifest files.",
        section="Stage IO",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default="template-specific",
        options=(
            ConfigOption("file", "One managed file."),
            ConfigOption("files", "Multiple discovered files."),
            ConfigOption("metric", "A metric value read from JSON."),
            ConfigOption("manifest", "A manifest JSON file."),
        ),
        required=True,
    ),
    ConfigField(
        path="stages.*.outputs.*.required",
        title="Output required flag",
        short_help="Controls whether missing output discovery fails the stage result.",
        when_to_change="Enable this for artifacts or metrics required by downstream stages or run acceptance.",
        section="Stage IO",
        level="intermediate",
        value_type="boolean",
        templates=ALL_STARTER_TEMPLATES,
        default="false",
        required=False,
    ),
    ConfigField(
        path="stages.*.outputs.*.file",
        title="Output JSON file",
        short_help="JSON file produced by the stage and read by output discovery.",
        when_to_change="Change this when the stage writes metrics or manifests to a different path.",
        section="Stage IO",
        level="common",
        value_type="path",
        templates=EVAL_TEMPLATES,
        default="eval/metrics.json",
        required=False,
    ),
    ConfigField(
        path="stages.*.outputs.*.json_path",
        title="Metric JSONPath",
        short_help="JSONPath used to read a metric value from the output file.",
        when_to_change="Change this when the metric lives under a different JSON key.",
        section="Stage IO",
        level="common",
        templates=EVAL_TEMPLATES,
        default="$.accuracy",
        required=False,
    ),
    ConfigField(
        path="stages.*.outputs.*.discover.globs",
        title="Output discovery globs",
        short_help="Glob patterns evaluated under the stage run directory.",
        when_to_change="Change these when the stage writes artifacts under a different directory or filename pattern.",
        section="Stage IO",
        level="common",
        value_type="list",
        templates=TRAIN_TEMPLATES,
        default="checkpoints/**/*.pt",
        required=False,
    ),
    ConfigField(
        path="stages.*.outputs.*.discover.select",
        title="Output discovery selector",
        short_help="Selects one path from discovered output glob matches.",
        when_to_change="Use first or last when lexicographic ordering is the desired selection rule.",
        section="Stage IO",
        level="intermediate",
        templates=TRAIN_TEMPLATES,
        default="latest_step",
        options=(
            ConfigOption("latest_step", "Pick the path with the highest step number."),
            ConfigOption("first", "Pick the first sorted match."),
            ConfigOption("last", "Pick the last sorted match."),
        ),
        required=False,
    ),
)
