from __future__ import annotations

from typing import Final

from ...config_contract.defaults import (
    DEFAULT_CHECKPOINT_PATH,
    DEFAULT_INPUT_EXPECTS,
    DEFAULT_INPUT_INJECT_MODE,
    DEFAULT_OUTPUT_DISCOVER_SELECT,
    DEFAULT_OUTPUT_REQUIRED,
)
from ...config_contract.options import (
    INPUT_EXPECTS,
    INPUT_INJECT_MODES,
    INPUT_SOURCE_KINDS,
    OUTPUT_KINDS,
    OUTPUT_SELECTORS,
)
from ...config_contract.workflows import (
    ALL_STARTER_TEMPLATES,
    EVAL_TEMPLATES,
    STAGE_TRAIN,
    TEMPLATE_TRAIN_EVAL,
    TRAIN_TEMPLATES,
)
from ..models import ConfigField

FIELDS: Final[tuple[ConfigField, ...]] = (
    ConfigField(
        path="stages.*.depends_on",
        title="Stage dependencies",
        short_help="Upstream stage names that must complete before this stage is selected.",
        when_to_change="Set this when a stage consumes outputs from earlier stages.",
        section="Stage IO",
        level="intermediate",
        value_type="list",
        templates=(TEMPLATE_TRAIN_EVAL,),
        default_display="template-specific",
        required=False,
    ),
    ConfigField(
        path="stages.*.inputs.*.source.kind",
        title="Input source kind",
        short_help="Controls where a stage input is resolved from.",
        when_to_change="Use upstream_output for pipeline dependencies and external_path for user-provided files.",
        section="Stage IO",
        level="intermediate",
        templates=EVAL_TEMPLATES,
        default_display="template-specific",
        options=INPUT_SOURCE_KINDS,
        required=True,
    ),
    ConfigField(
        path="stages.*.inputs.*.source.stage",
        title="Input source stage",
        short_help="Producer stage name for an upstream output input.",
        when_to_change="Change this when the input should consume a different upstream producer.",
        section="Stage IO",
        level="intermediate",
        templates=(TEMPLATE_TRAIN_EVAL,),
        default_display=STAGE_TRAIN,
        required=None,
    ),
    ConfigField(
        path="stages.*.inputs.*.source.output",
        title="Input source output",
        short_help="Producer output name resolved from the upstream stage.",
        when_to_change="Change this when the producer stage exposes a different output contract.",
        section="Stage IO",
        level="intermediate",
        templates=(TEMPLATE_TRAIN_EVAL,),
        default_display="template-specific",
        required=None,
    ),
    ConfigField(
        path="stages.*.inputs.*.source.path",
        title="External input path",
        short_help="Explicit user-provided input path resolved relative to the config directory.",
        when_to_change="Replace the starter sample path with the real artifact path before submit.",
        section="Stage IO",
        level="common",
        value_type="path",
        templates=EVAL_TEMPLATES,
        default_display=DEFAULT_CHECKPOINT_PATH,
        required=None,
    ),
    ConfigField(
        path="stages.*.inputs.*.expects",
        title="Input expected shape",
        short_help="Declares the resolved input shape expected by the consuming stage.",
        when_to_change="Change this when passing a manifest payload or scalar value instead of a filesystem path.",
        section="Stage IO",
        level="intermediate",
        templates=EVAL_TEMPLATES,
        default_value=DEFAULT_INPUT_EXPECTS,
        options=INPUT_EXPECTS,
        required=False,
    ),
    ConfigField(
        path="stages.*.inputs.*.required",
        title="Input required flag",
        short_help="Controls whether a missing resolved input fails the stage plan.",
        when_to_change="Enable this for inputs that are mandatory for correct stage execution.",
        section="Stage IO",
        level="intermediate",
        value_type="boolean",
        templates=EVAL_TEMPLATES,
        default_value=False,
        required=False,
    ),
    ConfigField(
        path="stages.*.inputs.*.inject.mode",
        title="Input injection mode",
        short_help="Controls how a resolved input is injected into the stage process.",
        when_to_change="Use json for structured payloads or value for scalar values.",
        section="Stage IO",
        level="intermediate",
        templates=EVAL_TEMPLATES,
        default_value=DEFAULT_INPUT_INJECT_MODE,
        options=INPUT_INJECT_MODES,
        required=False,
    ),
    ConfigField(
        path="stages.*.inputs.*.inject.flag",
        title="Input CLI flag",
        short_help="CLI flag name used to pass the resolved input; the value maps exactly to the flag name, with `--` added only when no dash prefix is present.",
        when_to_change="Use the exact spelling accepted by your script, matching the same flag rule as stages.*.entry.args.",
        section="Stage IO",
        level="common",
        templates=EVAL_TEMPLATES,
        default_display="template-specific",
        required=False,
    ),
    ConfigField(
        path="stages.*.inputs.*.inject.env",
        title="Input environment variable",
        short_help="Environment variable used to pass the resolved input to the stage process.",
        when_to_change="Change this when the script expects a different environment variable name.",
        section="Stage IO",
        level="intermediate",
        templates=EVAL_TEMPLATES,
        default_display="template-specific",
        required=False,
    ),
    ConfigField(
        path="stages.*.outputs.*.kind",
        title="Output kind",
        short_help="Declares the shape of a managed stage output.",
        when_to_change="Use file/files for artifacts, metric for JSON scalar metrics, and manifest for manifest files.",
        section="Stage IO",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default_display="template-specific",
        options=OUTPUT_KINDS,
        required=True,
    ),
    ConfigField(
        path="stages.*.outputs.*.required",
        title="Output required flag",
        short_help="Controls whether missing output discovery fails the stage result.",
        when_to_change="Enable this for artifacts or metrics required by downstream stages or run acceptance.",
        section="Stage IO",
        level="intermediate",
        value_type="boolean",
        templates=ALL_STARTER_TEMPLATES,
        default_value=DEFAULT_OUTPUT_REQUIRED,
        required=False,
    ),
    ConfigField(
        path="stages.*.outputs.*.file",
        title="Output JSON file",
        short_help="JSON file produced by the stage and read by output discovery.",
        when_to_change="Change this when the stage writes metrics or manifests to a different path.",
        section="Stage IO",
        level="common",
        value_type="path",
        templates=EVAL_TEMPLATES,
        default_display="template-specific",
        required=False,
    ),
    ConfigField(
        path="stages.*.outputs.*.json_path",
        title="Metric JSONPath",
        short_help="JSONPath used to read a metric value from the output file.",
        when_to_change="Change this when the metric lives under a different JSON key.",
        section="Stage IO",
        level="common",
        templates=EVAL_TEMPLATES,
        default_display="template-specific",
        required=False,
    ),
    ConfigField(
        path="stages.*.outputs.*.discover.globs",
        title="Output discovery globs",
        short_help="Glob patterns evaluated under the stage run directory.",
        when_to_change="Change these when the stage writes artifacts under a different directory or filename pattern.",
        section="Stage IO",
        level="common",
        value_type="list",
        templates=TRAIN_TEMPLATES,
        default_display="template-specific",
        required=False,
    ),
    ConfigField(
        path="stages.*.outputs.*.discover.select",
        title="Output discovery selector",
        short_help="Selects one path from discovered output glob matches.",
        when_to_change="Use first or last when lexicographic ordering is the desired selection rule.",
        section="Stage IO",
        level="intermediate",
        templates=TRAIN_TEMPLATES,
        default_value=DEFAULT_OUTPUT_DISCOVER_SELECT,
        options=OUTPUT_SELECTORS,
        required=False,
    ),
)
