from __future__ import annotations

import warnings
from pathlib import Path

from ...identity import PACKAGE_NAME, __version__, version_mismatch_warning
from ...pipeline.records import RunPlan
from ...storage import open_batch_storage


def validate_record_generator(plan: RunPlan) -> None:
    if plan.generated_by.name != PACKAGE_NAME:
        raise ValueError(
            f"run record was generated by {plan.generated_by.name}, "
            f"but the current executor expects {PACKAGE_NAME}"
        )
    if plan.generated_by.version != __version__:
        warnings.warn(
            version_mismatch_warning(
                generated_by_name=plan.generated_by.name,
                generated_by_version=plan.generated_by.version,
            ),
            stacklevel=2,
        )


def load_plan(batch_root: Path, *, group_index: int, task_index: int) -> RunPlan:
    """Load a RunPlan by its logical locator (batch_root, group_index, task_index).

    Uses ``open_batch_storage`` to auto-detect the storage engine
    (filesystem or SQLite) from the batch's on-disk layout. This replaces the
    legacy ``--record PATH`` approach and decouples the executor from the
    physical file layout.
    """
    store = open_batch_storage(batch_root).planning
    plan = store.load_plan_for_array_task(batch_root, group_index, task_index)
    if plan is None:
        raise FileNotFoundError(
            f"No run plan found for batch_root={batch_root} "
            f"group_index={group_index} task_index={task_index}"
        )
    validate_record_generator(plan)
    return plan
