from __future__ import annotations

import json
import warnings
from pathlib import Path

from ...identity import PACKAGE_NAME, __version__, version_mismatch_warning
from ...pipeline.records import (
    RunPlan,
    batch_root_from_record_path,
    bind_run_plan_to_batch,
    deserialize_run_plan,
)


def validate_record_generator(plan: RunPlan) -> None:
    if plan.generated_by.name != PACKAGE_NAME:
        raise ValueError(
            f"run record was generated by {plan.generated_by.name}, "
            f"but the current executor expects {PACKAGE_NAME}"
        )
    if plan.generated_by.version != __version__:
        warnings.warn(
            version_mismatch_warning(
                generated_by_name=plan.generated_by.name,
                generated_by_version=plan.generated_by.version,
            ),
            stacklevel=2,
        )


def load_plan(record_path: Path) -> RunPlan:
    if not record_path.exists():
        raise FileNotFoundError(f"Run record not found: {record_path}")

    payload = json.loads(record_path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Invalid run record format: {record_path}")
    resolved_plan = deserialize_run_plan(payload)
    try:
        batch_root = batch_root_from_record_path(record_path)
    except ValueError:
        bound_plan = resolved_plan
    else:
        bound_plan = bind_run_plan_to_batch(batch_root, resolved_plan)
    validate_record_generator(bound_plan)
    return bound_plan
