from __future__ import annotations

INSTANCE_PLANNED = "planned"
INSTANCE_READY = "ready"
INSTANCE_SUBMITTED = "submitted"
INSTANCE_RUNNING = "running"
INSTANCE_SUCCESS = "success"
INSTANCE_FAILED = "failed"
INSTANCE_SKIPPED = "skipped"
INSTANCE_BLOCKED = "blocked"
INSTANCE_TERMINAL_STATES = (
    INSTANCE_SUCCESS,
    INSTANCE_FAILED,
    INSTANCE_SKIPPED,
    INSTANCE_BLOCKED,
)
INSTANCE_STATES = (
    INSTANCE_PLANNED,
    INSTANCE_READY,
    INSTANCE_SUBMITTED,
    INSTANCE_RUNNING,
    INSTANCE_SUCCESS,
    INSTANCE_FAILED,
    INSTANCE_SKIPPED,
    INSTANCE_BLOCKED,
)

DEPENDENCY_WAITING = "waiting"
DEPENDENCY_READY = "ready"
DEPENDENCY_RESOLVED = "resolved"
DEPENDENCY_BLOCKED = "blocked"
DEPENDENCY_STATES = (
    DEPENDENCY_WAITING,
    DEPENDENCY_READY,
    DEPENDENCY_RESOLVED,
    DEPENDENCY_BLOCKED,
)

DISPATCH_SUBMITTING = "submitting"
DISPATCH_SUBMITTED = "submitted"
DISPATCH_TERMINAL = "terminal"
DISPATCH_FAILED = "failed"
DISPATCH_ACTIVE_STATES = (DISPATCH_SUBMITTING, DISPATCH_SUBMITTED)
DISPATCH_STATES = (
    DISPATCH_SUBMITTING,
    DISPATCH_SUBMITTED,
    DISPATCH_TERMINAL,
    DISPATCH_FAILED,
)
DISPATCH_ROLE_INITIAL = "initial"
DISPATCH_ROLE_DISPATCH = "dispatch"
DISPATCH_ROLES = (DISPATCH_ROLE_INITIAL, DISPATCH_ROLE_DISPATCH)

TERMINAL_AGGREGATION_PENDING = "pending"
TERMINAL_AGGREGATION_SUBMITTED = "submitted"
TERMINAL_AGGREGATION_FAILED = "failed"
TERMINAL_AGGREGATION_UNCERTAIN = "uncertain"
TERMINAL_AGGREGATION_DISABLED = "disabled"
TERMINAL_AGGREGATION_STATES = (
    TERMINAL_AGGREGATION_PENDING,
    TERMINAL_AGGREGATION_SUBMITTED,
    TERMINAL_AGGREGATION_FAILED,
    TERMINAL_AGGREGATION_UNCERTAIN,
    TERMINAL_AGGREGATION_DISABLED,
)

__all__ = (
    "DEPENDENCY_BLOCKED",
    "DEPENDENCY_READY",
    "DEPENDENCY_RESOLVED",
    "DEPENDENCY_STATES",
    "DEPENDENCY_WAITING",
    "DISPATCH_ACTIVE_STATES",
    "DISPATCH_FAILED",
    "DISPATCH_ROLE_DISPATCH",
    "DISPATCH_ROLE_INITIAL",
    "DISPATCH_ROLES",
    "DISPATCH_STATES",
    "DISPATCH_SUBMITTED",
    "DISPATCH_SUBMITTING",
    "DISPATCH_TERMINAL",
    "INSTANCE_BLOCKED",
    "INSTANCE_FAILED",
    "INSTANCE_PLANNED",
    "INSTANCE_READY",
    "INSTANCE_RUNNING",
    "INSTANCE_SKIPPED",
    "INSTANCE_STATES",
    "INSTANCE_SUBMITTED",
    "INSTANCE_SUCCESS",
    "INSTANCE_TERMINAL_STATES",
    "TERMINAL_AGGREGATION_DISABLED",
    "TERMINAL_AGGREGATION_FAILED",
    "TERMINAL_AGGREGATION_PENDING",
    "TERMINAL_AGGREGATION_STATES",
    "TERMINAL_AGGREGATION_SUBMITTED",
    "TERMINAL_AGGREGATION_UNCERTAIN",
)
