from __future__ import annotations

# ruff: noqa: F401

from ..workflow_enums import (
    DEPENDENCY_BLOCKED,
    DEPENDENCY_READY,
    DEPENDENCY_RESOLVED,
    DEPENDENCY_STATES,
    DEPENDENCY_WAITING,
    DISPATCH_ACTIVE_STATES,
    DISPATCH_FAILED,
    DISPATCH_ROLE_DISPATCH,
    DISPATCH_ROLE_INITIAL,
    DISPATCH_ROLES,
    DISPATCH_STATES,
    DISPATCH_SUBMITTED,
    DISPATCH_SUBMITTING,
    DISPATCH_TERMINAL,
    INSTANCE_BLOCKED,
    INSTANCE_FAILED,
    INSTANCE_PLANNED,
    INSTANCE_READY,
    INSTANCE_RUNNING,
    INSTANCE_SKIPPED,
    INSTANCE_STATES,
    INSTANCE_SUBMITTED,
    INSTANCE_SUCCESS,
    INSTANCE_TERMINAL_STATES,
    RELEASE_PER_GROUP,
    RELEASE_PER_RUN,
    RELEASE_PER_STAGE,
    RELEASE_POLICIES,
    RELEASE_WINDOWED,
    TERMINAL_AGGREGATION_DISABLED,
    TERMINAL_AGGREGATION_FAILED,
    TERMINAL_AGGREGATION_PENDING,
    TERMINAL_AGGREGATION_STATES,
    TERMINAL_AGGREGATION_SUBMITTED,
    TERMINAL_AGGREGATION_UNCERTAIN,
    WORKFLOW_STATES,
)

__all__ = [name for name in globals() if name.isupper()]
