"""Shared CLI argument builders and batch materialization helpers."""
from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from ..errors import ConfigContractError
from ..identity import __version__, regenerate_after_upgrade_note
from ..pipeline.materialization import MaterializationResult, materialize_batch, print_dry_run
from ..pipeline.planning import PlannedBatch
from ..storage import create_planning_store
from ..sweep import deep_set, parse_override
from ..templating import build_template_env


def load_raw_cfg(config_path: Path) -> dict:
    """Load a YAML config file as a plain dict, without applying any overrides."""
    text = config_path.read_text(encoding="utf-8")
    cfg = yaml.safe_load(text)
    if not isinstance(cfg, dict):
        raise ConfigContractError(f"Config must be a YAML mapping: {config_path}")
    return cfg


def load_effective_cfg(config_path: Path, cli_overrides: list[str]) -> dict:
    """
    Load YAML config and apply CLI overrides, producing the effective config.

    This represents the user's declared intent — raw YAML merged with any
    ``--set`` overrides — and is the single config view that all pre-compile
    checks (completeness, correctness, advisory) should operate on.

    The compiler receives ``(config_path, cli_overrides)`` separately because
    it tracks override provenance for diagnostics and replay.
    """
    cfg = load_raw_cfg(config_path)
    for override in cli_overrides:
        key, value = parse_override(override)
        deep_set(cfg, key, value)
    return cfg


def add_config_override_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--set",
        action="append",
        default=[],
        help="Override config by dot-path, e.g. --set run.args.lr=0.004",
    )
    parser.add_argument(
        "--project_root",
        default=None,
        help="Override project root used to resolve relative paths (default: config file directory)",
    )


def add_dry_run_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--dry_run",
        action="store_true",
        help="Expand runs and print commands without writing files",
    )


def add_common_args(parser: argparse.ArgumentParser) -> None:
    add_config_override_args(parser)
    add_dry_run_arg(parser)


def materialize_or_print_batch(
    *,
    planned_batch: PlannedBatch,
    dry_run: bool,
) -> MaterializationResult | None:
    if dry_run:
        print_dry_run(planned_run.plan for planned_run in planned_batch.planned_runs)
        return None

    env = build_template_env()
    planning_store = create_planning_store(planned_batch.storage_config, env)
    return materialize_batch(
        planned_batch=planned_batch,
        planning_store=planning_store,
    )


def print_batch_ready(*, dispatch: MaterializationResult, sbatch_dir: Path, retry: bool = False) -> None:
    if retry:
        print(f"[OK] Generated retry batch with {len(dispatch.array_groups_meta)} array sbatch file(s) in: {sbatch_dir}")
    else:
        print(f"[OK] Generated {len(dispatch.array_groups_meta)} array sbatch file(s) in: {sbatch_dir}")
    print(f"[OK] Generated by: slurmforge {__version__}")
    print(f"[OK] Submit all via: {dispatch.submit_script}")
    print(f"[OK] Batch manifest: {dispatch.manifest_path}")
    print(f"[NOTE] {regenerate_after_upgrade_note()}")
