from __future__ import annotations

from typing import Final

from ..default_values import DEFAULT_ENVIRONMENT_NAME
from ..option_sets import (
    DISPATCH_POLICIES,
    DISPATCH_POLICY_SERIALIZE_GROUPS,
    RELEASE_POLICY_PER_RUN,
    RELEASE_POLICY_OPTIONS,
)
from ..workflows import ALL_STARTER_TEMPLATES, TEMPLATE_TRAIN_EVAL
from ..models import ConfigField

FIELDS: Final[tuple[ConfigField, ...]] = (
    ConfigField(
        path="dispatch.max_available_gpus",
        title="Global GPU budget",
        short_help="GPU budget used to serialize Slurm array groups when a plan exceeds available GPUs.",
        when_to_change="Set this to the practical cluster budget you want this workflow to consume.",
        section="Dispatch",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default_value=1,
    ),
    ConfigField(
        path="dispatch.overflow_policy",
        title="GPU overflow policy",
        short_help="Controls planner behavior when run groups exceed the declared GPU budget.",
        when_to_change="Use error for strict admission control, or best_effort when the scheduler should absorb overflow.",
        section="Dispatch",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default_value=DISPATCH_POLICY_SERIALIZE_GROUPS,
        options=DISPATCH_POLICIES,
    ),
    ConfigField(
        path="dispatch.release_policy",
        title="Release policy",
        short_help="Controls when downstream stage instances become eligible for dispatch.",
        when_to_change="Use per_run for streaming eval, per_stage for all-train-then-eval behavior, or per_group/windowed for batched release.",
        section="Dispatch",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default_value=RELEASE_POLICY_PER_RUN,
        options=RELEASE_POLICY_OPTIONS,
    ),
    ConfigField(
        path="dispatch.window_size",
        title="Windowed release size",
        short_help="Number of ready downstream stage instances that trigger a windowed dispatch.",
        when_to_change="Use this with release_policy=windowed to batch streaming eval submissions.",
        section="Dispatch",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default_value=1,
        value_type="integer",
    ),
    ConfigField(
        path="dispatch.window_seconds",
        title="Windowed release wait",
        short_help="Maximum seconds a ready downstream stage instance waits before windowed dispatch.",
        when_to_change="Use this with release_policy=windowed when slow trickle completion should still flush eval work.",
        section="Dispatch",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default_value=0,
        value_type="integer",
    ),
    ConfigField(
        path="orchestration.control",
        title="Control job resources",
        short_help="Slurm resources for short-lived CPU-only pipeline control jobs.",
        when_to_change="Change this when gate or notification jobs need a different control queue, time limit, or environment.",
        section="Dispatch",
        level="advanced",
        templates=(TEMPLATE_TRAIN_EVAL,),
        default_display="partition=null, cpus=1, mem=2G, time_limit=00:10:00",
    ),
    ConfigField(
        path="orchestration.control.partition",
        title="Control partition",
        short_help="Optional Slurm partition for CPU-only pipeline control jobs.",
        when_to_change="Set this only when control jobs must use a named CPU/control queue.",
        section="Dispatch",
        level="advanced",
        templates=(TEMPLATE_TRAIN_EVAL,),
        default_value=None,
    ),
    ConfigField(
        path="orchestration.control.cpus",
        title="Control CPU count",
        short_help="CPU count requested by short-lived pipeline control jobs.",
        when_to_change="Increase this only if gate reconciliation or planning overhead requires it.",
        section="Dispatch",
        level="advanced",
        value_type="integer",
        templates=(TEMPLATE_TRAIN_EVAL,),
        default_value=1,
    ),
    ConfigField(
        path="orchestration.control.mem",
        title="Control memory",
        short_help="Memory requested by short-lived pipeline control jobs.",
        when_to_change="Increase this when gate planning or notification work needs more memory.",
        section="Dispatch",
        level="advanced",
        templates=(TEMPLATE_TRAIN_EVAL,),
        default_value="2G",
    ),
    ConfigField(
        path="orchestration.control.time_limit",
        title="Control time limit",
        short_help="Slurm time limit requested by short-lived pipeline control jobs.",
        when_to_change="Increase this only if gate reconciliation, eval materialization, or notifications need more time.",
        section="Dispatch",
        level="advanced",
        value_type="duration",
        templates=(TEMPLATE_TRAIN_EVAL,),
        default_value="00:10:00",
    ),
    ConfigField(
        path="orchestration.control.environment",
        title="Control environment",
        short_help="Environment profile loaded before pipeline control jobs run.",
        when_to_change="Change this when gate jobs need cluster modules or setup scripts.",
        section="Dispatch",
        level="advanced",
        templates=(TEMPLATE_TRAIN_EVAL,),
        default_value=DEFAULT_ENVIRONMENT_NAME,
    ),
)
