from __future__ import annotations

from typing import Final

from ..workflows import ALL_STARTER_TEMPLATES
from ..models import ConfigField

FIELDS: Final[tuple[ConfigField, ...]] = (
    ConfigField(
        path="stages.*.resources",
        title="Stage resources",
        short_help="Slurm partition, CPU, GPU, memory, and time settings for each stage.",
        when_to_change="Set these before real cluster runs so train and eval request the right resources.",
        section="Resources",
        level="common",
        templates=ALL_STARTER_TEMPLATES,
        default_display="template-specific",
        first_edit=True,
    ),
    ConfigField(
        path="stages.*.resources.partition",
        title="Stage partition",
        short_help="Slurm partition or queue for each stage task.",
        when_to_change="Set this to the queue appropriate for the stage workload.",
        section="Resources",
        level="common",
        templates=ALL_STARTER_TEMPLATES,
        default_value="gpu",
    ),
    ConfigField(
        path="stages.*.resources.account",
        title="Stage Slurm account",
        short_help="Slurm account charged for each stage task.",
        when_to_change="Set this when your cluster requires an account for GPU or partition access.",
        section="Resources",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default_display="null",
    ),
    ConfigField(
        path="stages.*.resources.qos",
        title="Stage Slurm QoS",
        short_help="Slurm QoS requested for each stage task.",
        when_to_change="Set this when your cluster uses QoS for priority, limits, or preemption policy.",
        section="Resources",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default_display="null",
    ),
    ConfigField(
        path="stages.*.resources.gpu_type",
        title="Stage GPU type",
        short_help="Named GPU type from hardware.gpu_types used for GPU sizing and Slurm constraints.",
        when_to_change="Set this when a stage must target a specific accelerator family.",
        section="Resources",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default_display="",
    ),
    ConfigField(
        path="stages.*.resources.nodes",
        title="Stage node count",
        short_help="Number of nodes requested by each stage task.",
        when_to_change="Increase for multi-node launchers and distributed workloads.",
        section="Resources",
        level="intermediate",
        value_type="integer",
        templates=ALL_STARTER_TEMPLATES,
        default_value=1,
    ),
    ConfigField(
        path="stages.*.resources.gpus_per_node",
        title="Stage GPUs per node",
        short_help="GPU count per node, or auto when GPU sizing is configured.",
        when_to_change="Set this to match the model memory and launcher requirements.",
        section="Resources",
        level="common",
        value_type="integer-or-auto",
        templates=ALL_STARTER_TEMPLATES,
        default_value=1,
    ),
    ConfigField(
        path="stages.*.resources.cpus_per_task",
        title="Stage CPUs per task",
        short_help="CPU count requested for each stage task.",
        when_to_change="Set this to match dataloader, preprocessing, or evaluation CPU needs.",
        section="Resources",
        level="common",
        value_type="integer",
        templates=ALL_STARTER_TEMPLATES,
        default_value=1,
    ),
    ConfigField(
        path="stages.*.resources.mem",
        title="Stage memory",
        short_help="Memory requested for each stage task.",
        when_to_change="Set this to the memory required by model loading, training, or evaluation.",
        section="Resources",
        level="common",
        templates=ALL_STARTER_TEMPLATES,
        default_display="template-specific",
    ),
    ConfigField(
        path="stages.*.resources.constraint",
        title="Stage Slurm constraint",
        short_help="Raw Slurm constraint requested for each stage task.",
        when_to_change="Use this for cluster-specific node feature constraints that are not covered by gpu_type.",
        section="Resources",
        level="advanced",
        templates=ALL_STARTER_TEMPLATES,
        default_display="null",
    ),
    ConfigField(
        path="stages.*.resources.extra_sbatch_args",
        title="Extra sbatch arguments",
        short_help="Additional raw sbatch arguments appended to each stage task script.",
        when_to_change="Use this for site-specific Slurm flags that do not have a first-class config field.",
        section="Resources",
        level="advanced",
        value_type="list",
        templates=ALL_STARTER_TEMPLATES,
        default_display="[]",
    ),
    ConfigField(
        path="stages.*.resources.time_limit",
        title="Stage time limit",
        short_help="Slurm time limit requested for each stage task.",
        when_to_change="Set this to the expected wall time plus a practical safety margin.",
        section="Resources",
        level="common",
        value_type="duration",
        templates=ALL_STARTER_TEMPLATES,
        default_value="01:00:00",
    ),
)
