from __future__ import annotations

from typing import Final

from ..default_values import (
    DEFAULT_EVAL_SCRIPT,
    DEFAULT_STAGE_ENABLED,
    DEFAULT_STAGE_ENTRY_TYPE,
    DEFAULT_STAGE_ENTRY_WORKDIR,
    DEFAULT_STAGE_ENVIRONMENT,
    DEFAULT_STAGE_RUNTIME,
    DEFAULT_TRAIN_SCRIPT,
)
from ..option_sets import ENTRY_TYPES
from ..workflows import (
    ALL_STARTER_TEMPLATES,
    EVAL_TEMPLATES,
    TRAIN_TEMPLATES,
)
from ..models import ConfigField

FIELDS: Final[tuple[ConfigField, ...]] = (
    ConfigField(
        path="stages.train.entry.script",
        title="Train script",
        short_help="Python script used for the train stage.",
        when_to_change="Point this at your real training entrypoint after replacing the generated demo code.",
        section="Stages",
        level="common",
        templates=TRAIN_TEMPLATES,
        default_value=DEFAULT_TRAIN_SCRIPT,
        required=True,
        first_edit=True,
    ),
    ConfigField(
        path="stages.eval.entry.script",
        title="Eval script",
        short_help="Python script used for the eval stage.",
        when_to_change="Point this at your real evaluation entrypoint after replacing the generated demo code.",
        section="Stages",
        level="common",
        templates=EVAL_TEMPLATES,
        default_value=DEFAULT_EVAL_SCRIPT,
        required=True,
        first_edit=True,
    ),
    ConfigField(
        path="stages.*.kind",
        title="Stage kind",
        short_help="Stage role used by starter workflows and command selection.",
        when_to_change="Change only when defining a new stage role supported by the orchestration path.",
        section="Stages",
        level="advanced",
        templates=ALL_STARTER_TEMPLATES,
        default_display="template-specific",
    ),
    ConfigField(
        path="stages.*.enabled",
        title="Stage enabled flag",
        short_help="Controls whether the stage participates in planning.",
        when_to_change="Disable a stage only when intentionally excluding it from this config.",
        section="Stages",
        level="intermediate",
        value_type="boolean",
        templates=ALL_STARTER_TEMPLATES,
        default_value=DEFAULT_STAGE_ENABLED,
    ),
    ConfigField(
        path="stages.*.environment",
        title="Stage environment",
        short_help="Environment profile used before the stage runs.",
        when_to_change="Change this when a stage needs a different module/source/env setup.",
        section="Stages",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default_value=DEFAULT_STAGE_ENVIRONMENT,
    ),
    ConfigField(
        path="stages.*.runtime",
        title="Stage user runtime",
        short_help="User runtime profile used to execute the stage script.",
        when_to_change="Change this when a stage needs a different Python runtime or script environment.",
        section="Stages",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default_value=DEFAULT_STAGE_RUNTIME,
    ),
    ConfigField(
        path="stages.*.entry.script",
        title="Stage script",
        short_help="Script path resolved relative to the config file directory.",
        when_to_change="Point this at your real stage entrypoint.",
        section="Stages",
        level="common",
        value_type="path",
        templates=ALL_STARTER_TEMPLATES,
        default_display="template-specific",
        required=None,
    ),
    ConfigField(
        path="stages.*.entry.command",
        title="Stage command",
        short_help="Shell command or argv list used when entry.type is command.",
        when_to_change="Use this for non-Python stages or wrappers that should run as a raw command.",
        section="Stages",
        level="intermediate",
        value_type="command",
        templates=ALL_STARTER_TEMPLATES,
        default_display="contextual",
        required=None,
    ),
    ConfigField(
        path="stages.*.entry.workdir",
        title="Stage working directory",
        short_help="Working directory used when launching the stage command.",
        when_to_change="Change this when scripts should run from a directory other than the config directory.",
        section="Stages",
        level="intermediate",
        value_type="path",
        templates=ALL_STARTER_TEMPLATES,
        default_value=DEFAULT_STAGE_ENTRY_WORKDIR,
        required=False,
    ),
    ConfigField(
        path="stages.*.entry.type",
        title="Stage entry type",
        short_help="Controls how the stage command is interpreted.",
        when_to_change="Use command when the entrypoint is a shell command instead of a Python script.",
        section="Stages",
        level="intermediate",
        templates=ALL_STARTER_TEMPLATES,
        default_value=DEFAULT_STAGE_ENTRY_TYPE,
        required=False,
        options=ENTRY_TYPES,
    ),
    ConfigField(
        path="stages.*.entry.args",
        title="Stage arguments",
        short_help="Mapping passed to each stage script; each YAML key maps exactly to the CLI flag name, with `--` added only when no dash prefix is present.",
        when_to_change="Write the flag spelling your script accepts: max_length becomes --max_length, max-length becomes --max-length, and --raw.flag stays --raw.flag.",
        section="Stages",
        level="common",
        templates=ALL_STARTER_TEMPLATES,
        default_display="template-specific",
        required=False,
        first_edit=True,
    ),
    ConfigField(
        path="stages.*.before",
        title="Stage setup commands",
        short_help="Commands run before the main stage entrypoint inside the stage task.",
        when_to_change="Use this for lightweight per-task setup that belongs with a stage rather than a reusable environment.",
        section="Stages",
        level="advanced",
        value_type="list",
        templates=ALL_STARTER_TEMPLATES,
        default_display="[]",
        required=False,
    ),
    ConfigField(
        path="stages.*.before[].name",
        title="Stage setup step name",
        short_help="Optional label for a pre-entry setup command.",
        when_to_change="Set this when setup logs need a recognizable step name.",
        section="Stages",
        level="advanced",
        templates=ALL_STARTER_TEMPLATES,
        default_display="",
        required=False,
    ),
    ConfigField(
        path="stages.*.before[].run",
        title="Stage setup command",
        short_help="Shell command executed before the main stage entrypoint.",
        when_to_change="Use this for stage-local setup such as cache warmup or one-off file preparation.",
        section="Stages",
        level="advanced",
        value_type="command",
        templates=ALL_STARTER_TEMPLATES,
        default_display="required when before[] is present",
        required=True,
    ),
)
